### PR TITLE
Ch 12 exercises

### PR DESCRIPTION
**Pull request by Tillaert**
With exercises 1-8

### CODE REVIEW

**Comment by hzwaal4c** [comment]
Why create another branch after I've already created one for chapter 12?

**Comment by Tillaert** [comment]
I need to work on this more.

**Comment by Tillaert** [comment]
I've made this branch because it has some tests and exercises from the book's github.

**Comment by hzwaal4c** [comment]
OK, so now we have two forks with a skeleton `Applicative.java`. How are we going to deal with that?

**Pull request closed without merging**
